services:
  frontend-service:
    image: ${DOCKERHUB_USER}/langfens-frontend:${TAG}
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - path: frontend.env
        required: false
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"

 
